---

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
  # https://github.com/babel/eslint-plugin-babel
  - babel

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  jest: true

# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  # Functions and classes can be used before declaration
  # http://eslint.org/docs/rules/no-use-before-define
  no-use-before-define: # airbnb default: ['error', { functions: true, classes: true, variables: true }]
    - error
    -
      functions: false
      classes: false
      variables: true