---

node_js:
  - node

script:
  - make lint
  - make test

# single test suite, non-parallel build.

env:
  global:
    - CC_TEST_REPORTER_ID=4f9177cab8523a9404de37e5f0acb9ed425ac99aa99316421711c6456b89f20f
language: node_js

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-netcgo-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
